### ISSUE TITLE
drop down termianl on ganome 40.x wayland

### ISSUE THREAD

**Issue by tcstory** [tcstory/blog#18]
I like drop down terminal. I used to use tilda before gnome 40.x. after i swittched to gnome 40.x, I found that tilda can not work on it. so i decided to search for another solution. finally I got two.

the first solution is [ddterm](https://github.com/ddterm/gnome-shell-extension-ddterm), it works fine. 
and another sulution is [alacritty](https://github.com/alacritty/alacritty), it is high perfomance terminal. it also works fine in gnome wayland.

why I use the second solution is I found that wl-copy couldn't work well on ddterm, it cannot paste text from system clipboard when i pressed `p`, but the `ctrl-shift-v` worked.

the following is my alactritty configuration

```yaml
# 背景半透明，方便抄代码
window:
  opacity: 0.90

# 实时重载配置文件，不用重启测试配置选项
live_config_reload: true

# 主题，抄肥猫的主题配色
colors:
  # Default colors
  primary:
    background: '0x292C3E'
    foreground: '0xEBEBEB'

  # Cursor colors
  cursor:
    text: '0xFF261E'
    cursor: '0xFF261E'

  # Normal colors
  normal:
    black:   '0x0d0d0d'
    red:     '0xFF301B'
    green:   '0xA0E521'
    yellow:  '0xFFC620'
    blue:    '0x1BA6FA'
    magenta: '0x8763B8'
    cyan:    '0x21DEEF'
    white:   '0xEBEBEB'

  # Bright colors
  bright:
    black:   '0x6D7070'
    red:     '0xFF4352'
    green:   '0xB8E466'
    yellow:  '0xFFD750'
    blue:    '0x1BA6FA'
    magenta: '0xA578EA'
    cyan:    '0x73FBF1'
    white:   '0xFEFEF8'

# 字体设置为等宽字体，可以用命令 fc-list 查看你系统的字体
font:
  size: 13

  normal:
    family: IBM Plex Mono
    style: Regular

  bold:
    family: IBM Plex Mono
    style: Bold

  italic:
    family: IBM Plex Mono
    style: Italic


env:
  TERM: xterm-256color

```
